[package]
name = "aoc2023"
version = "0.1.0"
authors = ["André Vennberg <andre.vennberg@gmail.com>"]
edition = "2021"

[lib]
bench = false

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
bstr = "1.8.0"
arrayvec = "0.7.4"
rangemap = "1.4.0"
btoi = "0.4.3"
